export const MODAL_ADD_TODO = 'MODAL_ADD_TODO';
export const MODAL_NEW_CHAT = 'MODAL_NEW_CHAT';
export const MODAL_NEW_CHAT_HELP = 'MODAL_NEW_CHAT_HELP';
export const MODAL_START_CROPPING = 'MODAL_START_CROPPING';
export const MODAL_DELETE_ACCOUNT = 'MODAL_DELETE_ACCOUNT';
export const MODAL_CHATBOX_TIPS = 'MODAL_CHATBOX_TIPS';
export const MODAL_EDIT_TODO = 'MODAL_EDIT_TODO';
